import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { useState } from "react"
import AccountCreation from "../../src/sections/AccountForm"
import BizForm from "../../src/sections/BizForm"
import ChgPwdForm from "../../src/sections/ChgPwdForm"
import LoginForm from "../../src/sections/LoginForm"
import OtpForm from "../../src/sections/OtpForm"
import ResetPwd from "../../src/sections/ResetPwd"

export default function Home() {
  const [step, setStep] = useState(0)

  const nextStep = (e: React.SyntheticEvent) => {
    e.preventDefault()
    if (step < 5) setStep((prevState) => prevState + 1)
  }

  const prevStep = (e: React.SyntheticEvent) => {
    e.preventDefault()
    setStep((prevState) => prevState - 1)
  }

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex">
        <div className="hidden lg:block w-[40%] fixed h-[100vh] bg-[#0066F5] lg:px-14 lg:py-[4rem] xl:px-[4.75rem] xl:py-[7.4375rem] text-white">
          <h1 className="text-[1.5rem] font-semibold">Bizmore</h1>
          <h1 className="lg:mt-[8rem] xl:mt-[12.5rem] lg:text-[3.5rem] lg:leading-[4rem] xl:text-[4rem] xl:leading-[4.8125rem] font-semibold">
            Grow business seamlessly
          </h1>
          <p className="mt-[2.5rem] lg:text-[1rem] font-medium">
            Manage your business with bizmore, the only business management tools you really need
          </p>
        </div>
        <div className="w-full lg:w-[60%] lg:absolute lg:right-0 px-5 py-[4rem] lg:px-[6rem] xl:px-[8.125rem] xl:py-[7.4375rem]">
          {step == 0 && <AccountCreation onClick={nextStep} />}
          {step == 1 && <BizForm onClick={nextStep} />}
          {step == 2 && <LoginForm onClick={nextStep} />}
          {step == 3 && <ResetPwd onClick={nextStep} />}
          {step == 4 && <OtpForm onClick={nextStep} />}
          {step == 5 && <ChgPwdForm onClick={nextStep} />}
        </div>
      </div>
    </div>
  )
}
